version: '3.8'

services:
  portfolioai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./frontend:/app/frontend  # For development, mount frontend source
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload  # Enable auto-reload for development 